### ISSUE TITLE
Error: UnimplementedFeatureError: Nested memory arrays not yet implemented here.

### ISSUE THREAD

**Issue by isaiahcurry8** [iamdefinitelyahuman/nftoken#6]
I am getting this error when I try to run the "rangesOf" function. After a little research I have found that nested arrays only implemented internally and in storage, not memory. Is there another way implement nested arrays in memory? Here is the function I am using call "rangesOf" in NFToken:

    function rangesOf(address _owner) external view returns(uint64[2][] memory) {
        _ticketPoolCreator.rangesOf(_owner);
    }

**Comment by iamdefinitelyahuman** [comment]
Which version of `solc` are you using?

**Comment by isaiahcurry8** [comment]
version: "0.5.16"

**Comment by iamdefinitelyahuman** [comment]
That's very confusing! I'm not sure when support for nested memory arrays was added to Solidity, but I've tested locally as far back as `0.4.22` and it works fine.  `rangesOf` is very thoroughly covered in the test suite, and the tests are passing.

Can you share some info on your local environment? Are you using Brownie with Ganache, or a different setup?

**Comment by isaiahcurry8** [comment]
I am using Ganache

**Comment by iamdefinitelyahuman** [comment]
Which version of Ganache?
Which version of Brownie?  Or if a different framework, which one?
Which operating system are you using?

**Comment by isaiahcurry8** [comment]
Sorry. Using:
Ganache: 2.1.1
Truffle: 6.9.0
Windows 10

**Comment by iamdefinitelyahuman** [comment]
I'm not familiar with how Truffle handles setting the `solc` version, but based on the error message I'm guessing it's attempting to compile with an old version. I suggest looking up how to set / change the version.

Or better yet, try [Brownie](https://github.com/iamdefinitelyahuman/brownie) instead :)

**Comment by isaiahcurry8** [comment]
ok thanks

**Comment by isaiahcurry8** [comment]
Flattened the contract and put it on Remix and I got the same error. Must be something wrong in my contract

**Comment by iamdefinitelyahuman** [comment]
Ahh, I didn't realize you're working with a modified version of the contract.
